apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool-nfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool-nfs
  template:
    metadata:
      labels:
        app: multitool-nfs
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - name: nfs-data
          mountPath: /shared-data
      volumes:
      - name: nfs-data
        persistentVolumeClaim:
          claimName: nfs-pvc
